### PR TITLE
close on root sublevel closes db

### PR DESCRIPTION
**Pull request by juliangruber**
fixes https://github.com/dominictarr/level-sublevel/issues/78
fixes https://github.com/nolanlawson/leveldown-210/issues/1

I didn't implement the proper close on non-root sublevels, we can add this later on

### CODE REVIEW

**Comment by nolanlawson** [comment]
@juliangruber This is awesome; thanks for the fix! I can confirm that this solves the `LOCK: already held by process` error, although unfortunately the PouchDB tests are still failing, but due to a new error that looks easier to debug. (Seems that re-opened databases can't be written to for some reason; see https://github.com/pouchdb/pouchdb/pull/4236). I can try to take a stab at it when I get a chance.

Out of curiosity, what changed in leveldown/levelup to cause this bug? Everything was working okay in leveldown <1.0.0.

**Comment by juliangruber** [comment]
@nolanlawson it looks to me like this can only be a sublevel related change

**Comment by nolanlawson** [comment]
@juliangruber Yup, I was just running into issues upgrading from sublevel v5 to v6. I've resolved those issues and can confirm that your patch looks great; seems we'll finally be able to upgrade PouchDB to the latest levelup/leveldown!

**Comment by dominictarr** [comment]
Merged into 6.5.0!
There is still a small bug, that doesn't have level-sublevel running on the very latest level (it mostly works but one test fails - `test/inherit-encodings.js` Oh yeah, it is because of https://github.com/Level/codec/issues/7

**Comment by nolanlawson** [comment]
@dominictarr Thanks for the tip; I should go ahead and change everywhere in PouchDB we use `encoding` to `valueEncoding`, since I prefer being explicit anyway.

In any case I'm re-running the PouchDB test suite; looks like this PR will allow us to update, which is awesome.

**Comment by nolanlawson** [comment]
BTW the 5 -> 6 conversion also broke legacy `start`/`end`, so I had to upgrade to `lte`/`gte`. Also the `value()` changed from returning a string to returning an array of strings. Might be worth mentioning in the README.

**Comment by dominictarr** [comment]
@nolanlawson btw, sublevel@6 is a breaking change in the database encoding, so you'd have to run a migration to get an old database to use sublevel@6 - but you can use `require('level-sublevel/legacy')` and that will be backwards compatible.

Otherwise, i use `require('level-sublevel/bytewise')` to get bytewise encoded keys.

`start,end` ranges _should not break_. That is a bug. There are tests for this... can you post an issue?

what are you referring to as `value()`? do you mean key prefixes?

**Comment by nolanlawson** [comment]
Yeah, `start`and `end`were breaking when `reverse` was true. I can try to provide a test if you think it's important.

As for the other thing, I mistyped. I meant `prefix()`, not `value()`.

**Comment by dominictarr** [comment]
Hmm I though I had coverage for that. Would love a test case.

**Comment by nolanlawson** [comment]
@dominictarr Bam: https://github.com/dominictarr/level-sublevel/pull/98

**Comment by nolanlawson** [comment]
@dominictarr Wait, did you merge this PR? In npm I see 6.5.0, but in the git commits, the latest I see is 6.4.6.

**Comment by dominictarr** [comment]
sorry, merged!

**Comment by nolanlawson** [comment]
Cool, thanks! :)

**Pull request merged**
