### PR TITLE
bump levelup WIP

### PR DESCRIPTION
**Pull request by juliangruber**
WIP of updating to levelup@1.

I've started doing this because nsp was complaining:

``` bash
$ nsp audit-package
Name    Installed  Patched  Vulnerable Dependency
semver    2.3.2    >=4.3.2  level-sublevel@6.5.2 > levelup@0.19.0 > semver@2.3.2
```

### CODE REVIEW

**Comment by dominictarr** [comment]
I'd merge this right away if you merge https://github.com/Level/codec/pull/8

**Comment by juliangruber** [comment]
merged!

**Comment by dominictarr** [comment]
@juliangruber this doesn't pass the tests - mostly looks like there are a few names that changed from when you factored out codec etc,. can you get this working?

**Comment by juliangruber** [comment]
that's why i labeled it WIP, there's currently things more important to me than finishing this, so I put it up for anyone to continue working on it.

**Comment by juliangruber** [comment]
the next thing to do iirc is to fully switch from readstream to iteratorstream, passing in the correct encoding options

**Comment by dominictarr** [comment]
I noticed that iterator stream doesn't have `ReadStream#setIterator` which I needed. I think it probably just set `_iterator` but It would be good to have that locked in so it doesn't get broken in the future

**Comment by juliangruber** [comment]
would this be of use:? https://github.com/Level/deferred-leveldown/blob/master/deferred-iterator.js

**Comment by dominictarr** [comment]
it was like this: https://github.com/Level/levelup/blob/fb742b01990139b44b1816de87a6e1b2de629627/lib/read-stream.js#L31-L40

**Comment by juliangruber** [comment]
yeah, looks like you can do that with `AbstractIterator#setDb`

**Comment by ralphtheninja** [comment]
> I noticed that iterator stream doesn't have ReadStream#setIterator which I needed. I think it probably just set _iterator but It would be good to have that locked in so it doesn't get broken in the future

We could just put back `.setIterator()` in `iterator-stream`.

**Comment by dominictarr** [comment]
@ralphtheninja that would do it.

**Comment by vespakoen** [comment]
What is the status of this?

**Comment by ralphtheninja** [comment]
> What is the status of this?

It's unfinished

**Comment by vespakoen** [comment]
Fair enough, my question was too simplistic I guess, what I was really trying to as is what was left to be done.

It seems that the old read stream had support for deferred actions, deferred-leveldown (as suggested by @juliangruber) seems to have this as well, including the setIterator method (named as AbstractIterator#setDb)

Not too deep into this matter, but my simple mind would think that this should do the trick?
```js
var Iterator = require('deferred-leveldown/deferred-iterator');
Iterator.prototype.setIterator = Iterator.prototype.setDb;
```

Besides the setIterator method, are there other things that need to be done?

**Comment by ralphtheninja** [comment]
> Besides the setIterator method, are there other things that need to be done?

I don't remember at the top of my head. There was something more that didn't work with the tests iirc.

**Comment by vespakoen** [comment]
True, I get some errors in the "falsey value in key" test, wasn't able to resolve them.
This seems related: https://github.com/Level/codec/issues/7

**Comment by temyers** [comment]
I'm not familiar with the library but:
shell.js#142 currently reads:
```
stream = createStream(opts, nut.createDecoder(opts))
```

However the updated implementation of `createStream`, using `require('level-iterator-stream')` no longer follows that signature: https://github.com/Level/iterator-stream/blob/v2.0.0/index.js
```
function ReadStream (iterator, options) {
  if (!(this instanceof ReadStream)) return new ReadStream(iterator, options)
  options = options || {}
  Readable.call(this, extend(options, {
    objectMode: true
  }))
  this._iterator = iterator
  this._destroyed = false
  this._options = options
  this.on('end', this._cleanup.bind(this))
}
```

So I don't think the Decoder is being called.

What needs to be done?

**Pull request closed without merging**
